<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>ImplantiAI</AssemblyName>
    <RootNamespace>ImplantiAI</RootNamespace>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputPath>build\</OutputPath>
    <NoWarn>$(NoWarn);MSB3277;CS8600;CS8602;CS8603</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="acdbmgd">
      <HintPath>acdbmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acmgd">
      <HintPath>acmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcCoreMgd">
      <HintPath>accoremgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcWindows">
      <HintPath>AcWindows.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AdWindows">
      <HintPath>AdWindows.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
